### ISSUE TITLE
German keymap

### ISSUE THREAD

**Issue by RoboDave21** [schmjop/zmk-config#5]
May I ask where you found the information for how to make your German keymap? I would like to build my own with a few tweaks, but I don't know where you got the information what to write, for example after "#define DE_PLUS" to define that it outputs a "+".
Thanks.

**Comment by schmjop** [comment]
Hi @RoboDave21,
when pressing keys on your keyboard, a keyboard code is sent. ZMK has defined a [list of codes](https://zmk.dev/docs/codes/keyboard-keypad) that can be used in your keymap. However, these codes assume a [US qwerty layout](https://en.wikipedia.org/wiki/File:Qwerty.svg). If your computer has the keyboard input DE defined, the ZMK codes will output the wrong symbols.

In order to fix that I simply opened the [US qwerty layout](https://en.wikipedia.org/wiki/File:Qwerty.svg) and the [german layout](https://de.wikipedia.org/wiki/Tastaturbelegung#Tastaturbelegung_T1) side-by-side and changed each key accordingly. Thus, in the US layout pressing the key with the `]` is equal to pressing the `+` in the german layout.

In addition, MacOS uses yet another layout which is why some symbols had to be defined twice: Once for Windows and once for MacOS.

Hope this helps! Let me know if you need more info.

**Comment by RoboDave21** [comment]
Thanks for the great explanation.

Also meaning what I wanted to do doesn't work, because I wanted to add symbols like "Gedankenstrich" or an arrow "→".
I will take a look in the community.

Thanks anyway.

**Comment by schmjop** [comment]
I see what you mean. To send the arrow or a Gedankenstrich, you would have to send the corresponding keycode to the host PC. But I guess for those *special* symbol no such keycode exists. So my guess is that it's simply not possible.
I assume all possible keycodes would be listed [here](https://zmk.dev/docs/codes).

**Comment by schmjop** [comment]
Hi @RoboDave21,
I just came across [Unicode Sequences in the ZMK documentation](https://zmk.dev/docs/behaviors/macros#unicode-sequences). I guess this is exactly what you are looking for!
